### ISSUE TITLE
Can I get the real type of Typealias

### ISSUE THREAD

**Issue by Mx-Iris** [stackotter/swift-macro-toolkit#12]
I'm using AddAsyncMacro from the example, and it seems to only get the direct function type, if I use Optional or Typealias I get errors

<img width="1555" alt="iShot_2024-01-29_21 38 02" src="https://github.com/stackotter/swift-macro-toolkit/assets/61279231/5467bfa4-8230-49f6-a139-942ea0151e59">

**Comment by stackotter** [comment]
Hey, thanks for checking out the toolkit!

Unfortunately macros cannot know what a typealias expands to, so that case could not be handled without passing the macro extra information (as in making the macro take an optional argument where the dev can specify the underlying type of the completion handler).

However, optional completion handlers (without typealiases) could definitely be supported! (because all of the required type information is present in the syntax). The example macros aren’t very comprehensive because they’re only intended to demonstrate usage of the toolkit, but I’d happily accept a PR.

**Comment by stackotter** [comment]
I think my previous comment should answer your question, but feel free to reopen the issue if you have any related concerns
